import { Workout } from "../types";

// Sample workout data
export const SAMPLE_WORKOUTS: Workout[] = [
  {
    id: "push-day",
    name: "Push Day",
    description:
      "Upper body pushing exercises targeting chest, shoulders, and triceps",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 45,
    exercises: [
      {
        id: "bench-press",
        name: "Bench Press",
        sets: 4,
        reps: 8,
        restTime: 120,
        description: "Lie on bench, press bar from chest to arm extension",
      },
      {
        id: "shoulder-press",
        name: "Shoulder Press",
        sets: 3,
        reps: 10,
        restTime: 90,
        description: "Press weights overhead from shoulder height",
      },
      {
        id: "tricep-dips",
        name: "Tricep Dips",
        sets: 3,
        reps: 12,
        restTime: 60,
        description: "Lower body using triceps, push back up",
      },
      {
        id: "push-ups",
        name: "Push-ups",
        sets: 3,
        reps: 15,
        restTime: 60,
        description: "Classic push-up from plank position",
      },
      {
        id: "lateral-raises",
        name: "Lateral Raises",
        sets: 3,
        reps: 12,
        restTime: 45,
        description: "Raise arms to sides until parallel to floor",
      },
    ],
  },
  {
    id: "pull-day",
    name: "Pull Day",
    description:
      "Upper body pulling exercises targeting back, biceps, and rear delts",
    category: "strength",
    difficulty: "intermediate",
    estimatedDuration: 40,
    exercises: [
      {
        id: "pull-ups",
        name: "Pull-ups",
        sets: 4,
        reps: 6,
        restTime: 120,
        description: "Hang from bar, pull body up until chin over bar",
      },
      {
        id: "bent-over-rows",
        name: "Bent-over Rows",
        sets: 4,
        reps: 10,
        restTime: 90,
        description: "Bend at waist, pull weights to lower chest",
      },
      {
        id: "bicep-curls",
        name: "Bicep Curls",
        sets: 3,
        reps: 12,
        restTime: 60,
        description: "Curl weights from extended arm to shoulder",
      },
      {
        id: "face-pulls",
        name: "Face Pulls",
        sets: 3,
        reps: 15,
        restTime: 45,
        description: "Pull rope to face level, squeeze shoulder blades",
      },
      {
        id: "hammer-curls",
        name: "Hammer Curls",
        sets: 3,
        reps: 12,
        restTime: 60,
        description: "Curl with neutral grip, thumbs up",
      },
    ],
  },
  {
    id: "cardio-hiit",
    name: "HIIT Cardio",
    description: "High-intensity interval training for cardiovascular fitness",
    category: "cardio",
    difficulty: "advanced",
    estimatedDuration: 25,
    exercises: [
      {
        id: "jumping-jacks",
        name: "Jumping Jacks",
        sets: 4,
        reps: 0,
        duration: 45,
        restTime: 15,
        description: "Jump with feet apart, arms overhead",
      },
      {
        id: "burpees",
        name: "Burpees",
        sets: 4,
        reps: 0,
        duration: 30,
        restTime: 30,
        description: "Squat, jump back, push-up, jump forward, jump up",
      },
      {
        id: "mountain-climbers",
        name: "Mountain Climbers",
        sets: 4,
        reps: 0,
        duration: 45,
        restTime: 15,
        description: "Plank position, alternate bringing knees to chest",
      },
      {
        id: "high-knees",
        name: "High Knees",
        sets: 4,
        reps: 0,
        duration: 30,
        restTime: 30,
        description: "Run in place, bring knees up to waist level",
      },
      {
        id: "squat-jumps",
        name: "Squat Jumps",
        sets: 4,
        reps: 0,
        duration: 45,
        restTime: 15,
        description: "Squat down, explode up into jump",
      },
    ],
  },
];

// Modern, vibrant color palette for light and dark themes
export const COLORS = {
  light: {
    primary: "#6C63FF",
    primaryLight: "#8B7BFF",
    secondary: "#FF6B9D",
    secondaryLight: "#FF8BAD",
    background: "#FFFFFF",
    backgroundSecondary: "#F8F9FE",
    surface: "#FFFFFF",
    surfaceElevated: "#F8F9FE",
    text: "#1A1A1A",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    success: "#10B981",
    successLight: "#34D399",
    warning: "#F59E0B",
    warningLight: "#FBBF24",
    error: "#EF4444",
    errorLight: "#F87171",
    accent: "#8B5CF6",
    accentLight: "#A78BFA",
    gradient: {
      primary: ["#6C63FF", "#8B7BFF"],
      secondary: ["#FF6B9D", "#FF8BAD"],
      success: ["#10B981", "#34D399"],
      purple: ["#8B5CF6", "#A78BFA"],
      blue: ["#3B82F6", "#60A5FA"],
      pink: ["#EC4899", "#F472B6"],
      orange: ["#F59E0B", "#FBBF24"],
      teal: ["#14B8A6", "#5EEAD4"],
    },
  },
  dark: {
    primary: "#8B7BFF",
    primaryLight: "#A393FF",
    secondary: "#FF8BAD",
    secondaryLight: "#FFA4BD",
    background: "#0F0F0F",
    backgroundSecondary: "#1A1A1A",
    surface: "#1E1E1E",
    surfaceElevated: "#2A2A2A",
    text: "#FFFFFF",
    textSecondary: "#D1D5DB",
    textTertiary: "#9CA3AF",
    border: "#374151",
    borderLight: "#4B5563",
    success: "#34D399",
    successLight: "#6EE7B7",
    warning: "#FBBF24",
    warningLight: "#FCD34D",
    error: "#F87171",
    errorLight: "#FCA5A5",
    accent: "#A78BFA",
    accentLight: "#C4B5FD",
    gradient: {
      primary: ["#8B7BFF", "#A393FF"],
      secondary: ["#FF8BAD", "#FFA4BD"],
      success: ["#34D399", "#6EE7B7"],
      purple: ["#A78BFA", "#C4B5FD"],
      blue: ["#60A5FA", "#93C5FD"],
      pink: ["#F472B6", "#F9A8D4"],
      orange: ["#FBBF24", "#FCD34D"],
      teal: ["#5EEAD4", "#99F6E4"],
    },
  },
};

// Animation timings
export const ANIMATION_DURATION = {
  fast: 150,
  medium: 300,
  slow: 500,
  extraSlow: 800,
};

// App configuration
export const APP_CONFIG = {
  defaultRestTime: 60, // seconds
  maxRestTime: 300, // seconds
  minRestTime: 15, // seconds
  countdownWarning: 10, // seconds before end
  autoAdvance: true,
  soundEnabled: true,
  voiceEnabled: true,
};
